<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NationalitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['id' => '1', 'name' => ["ar" => "أفغانستان", "en" => "AFGHANISTAN"], 'code' => 'AF', 'status' => 'Active', 'order' => '2'],
            ['id' => '2', 'name' => ["ar" => "جزر أولان", "en" => "Aland"], 'code' => 'AX', 'status' => 'Active', 'order' => '2'],
            ['id' => '3', 'name' => ["ar" => "ألبانيا", "en" => "ALBANIA"], 'code' => 'AL', 'status' => 'Active', 'order' => '2'],
            ['id' => '4', 'name' => ["ar" => "الجزائر", "en" => "ALGERIA"], 'code' => 'DZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '5', 'name' => ["ar" => "جزر فرجين الأمريكية", "en" => "VIRGIN ISLANDS, U.S."], 'code' => 'VI', 'status' => 'Active', 'order' => '2'],
            ['id' => '6', 'name' => ["ar" => "ساموا الأمريكية", "en" => "AMERICAN SAMOA"], 'code' => 'AS', 'status' => 'Active', 'order' => '2'],
            ['id' => '7', 'name' => ["ar" => "أندورا", "en" => "ANDORRA"], 'code' => 'AD', 'status' => 'Active', 'order' => '2'],
            ['id' => '8', 'name' => ["ar" => "أنجولا", "en" => "ANGOLA"], 'code' => 'AO', 'status' => 'Active', 'order' => '2'],
            ['id' => '9', 'name' => ["ar" => "أنجويلا", "en" => "ANGUILLA"], 'code' => 'AI', 'status' => 'Active', 'order' => '2'],
            ['id' => '10', 'name' => ["ar" => "القطب الجنوبي", "en" => "ANTARCTICA"], 'code' => 'AQ', 'status' => 'Active', 'order' => '2'],
            ['id' => '11', 'name' => ["ar" => "أنتيجوا وبربودا", "en" => "ANTIGUA AND BARBUDA"], 'code' => 'AG', 'status' => 'Active', 'order' => '2'],
            ['id' => '12', 'name' => ["ar" => "الأرجنتين", "en" => "ARGENTINA"], 'code' => 'AR', 'status' => 'Active', 'order' => '2'],
            ['id' => '13', 'name' => ["ar" => "أرمينيا", "en" => "ARMENIA"], 'code' => 'AM', 'status' => 'Active', 'order' => '2'],
            ['id' => '14', 'name' => ["ar" => "آروبا", "en" => "ARUBA"], 'code' => 'AW', 'status' => 'Active', 'order' => '2'],
            ['id' => '15', 'name' => ["ar" => "أستراليا", "en" => "AUSTRALIA"], 'code' => 'AU', 'status' => 'Active', 'order' => '2'],
            ['id' => '16', 'name' => ["ar" => "أذربيجان", "en" => "AZERBAIJAN"], 'code' => 'AZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '17', 'name' => ["ar" => "الباهاما", "en" => "BAHAMAS"], 'code' => 'BS', 'status' => 'Active', 'order' => '2'],
            ['id' => '18', 'name' => ["ar" => "البحرين", "en" => "BAHRAIN"], 'code' => 'BH', 'status' => 'Active', 'order' => '1'],
            ['id' => '19', 'name' => ["ar" => "بنجلاديش", "en" => "BANGLADESH"], 'code' => 'BD', 'status' => 'Active', 'order' => '2'],
            ['id' => '20', 'name' => ["ar" => "بربادوس", "en" => "BARBADOS"], 'code' => 'BB', 'status' => 'Active', 'order' => '2'],
            ['id' => '21', 'name' => ["ar" => "بلجيكا", "en" => "BELGIUM"], 'code' => 'BE', 'status' => 'Active', 'order' => '2'],
            ['id' => '22', 'name' => ["ar" => "بليز", "en" => "BELIZE"], 'code' => 'BZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '23', 'name' => ["ar" => "بنين", "en" => "BENIN"], 'code' => 'BJ', 'status' => 'Active', 'order' => '2'],
            ['id' => '24', 'name' => ["ar" => "برمودا", "en" => "BERMUDA"], 'code' => 'BM', 'status' => 'Active', 'order' => '2'],
            ['id' => '25', 'name' => ["ar" => "بوتان", "en" => "BHUTAN"], 'code' => 'BT', 'status' => 'Active', 'order' => '2'],
            ['id' => '26', 'name' => ["ar" => "بوليفيا", "en" => "BOLIVIA"], 'code' => 'BO', 'status' => 'Active', 'order' => '2'],
            ['id' => '28', 'name' => ["ar" => "البوسنة والهرسك", "en" => "BOSNIA AND HERZEGOVINA"], 'code' => 'BA', 'status' => 'Active', 'order' => '2'],
            ['id' => '29', 'name' => ["ar" => "بتسوانا", "en" => "BOTSWANA"], 'code' => 'BW', 'status' => 'Active', 'order' => '2'],
            ['id' => '30', 'name' => ["ar" => "جزيرة بوفيه", "en" => "BOUVET ISLAND"], 'code' => 'BV', 'status' => 'Active', 'order' => '2'],
            ['id' => '31', 'name' => ["ar" => "البرازيل", "en" => "BRAZIL"], 'code' => 'BR', 'status' => 'Active', 'order' => '2'],
            ['id' => '32', 'name' => ["ar" => "جزر فرجين البريطانية", "en" => "VIRGIN ISLANDS, BRITISH"], 'code' => 'VG', 'status' => 'Active', 'order' => '2'],
            ['id' => '33', 'name' => ["ar" => "المحيط الهندي البريطاني", "en" => "BRITISH INDIAN OCEAN TERRITORY"], 'code' => 'IO', 'status' => 'Active', 'order' => '2'],
            ['id' => '34', 'name' => ["ar" => "بروناي", "en" => "BRUNEI DARUSSALAM"], 'code' => 'BN', 'status' => 'Active', 'order' => '2'],
            ['id' => '35', 'name' => ["ar" => "بلغاريا", "en" => "BULGARIA"], 'code' => 'BG', 'status' => 'Active', 'order' => '2'],
            ['id' => '36', 'name' => ["ar" => "بوركينا فاسو", "en" => "BURKINA FASO"], 'code' => 'BF', 'status' => 'Active', 'order' => '2'],
            ['id' => '37', 'name' => ["ar" => "بوروندي", "en" => "BURUNDI"], 'code' => 'BI', 'status' => 'Active', 'order' => '2'],
            ['id' => '38', 'name' => ["ar" => "كمبوديا", "en" => "CAMBODIA"], 'code' => 'KH', 'status' => 'Active', 'order' => '2'],
            ['id' => '39', 'name' => ["ar" => "كندا", "en" => "CANADA"], 'code' => 'CA', 'status' => 'Active', 'order' => '2'],
            ['id' => '40', 'name' => ["ar" => "جمهورية افريقيا الوسطى", "en" => "CENTRAL AFRICAN REPUBLIC"], 'code' => 'CF', 'status' => 'Active', 'order' => '2'],
            ['id' => '41', 'name' => ["ar" => "شيلي", "en" => "CHILE"], 'code' => 'CL', 'status' => 'Active', 'order' => '2'],
            ['id' => '42', 'name' => ["ar" => "الصين", "en" => "CHINA"], 'code' => 'CN', 'status' => 'Active', 'order' => '2'],
            ['id' => '43', 'name' => ["ar" => "جزيرة الكريسماس", "en" => "CHRISTMAS ISLAND"], 'code' => 'CX', 'status' => 'Active', 'order' => '2'],
            ['id' => '44', 'name' => ["ar" => "جزر كوكوس", "en" => "COCOS (KEELING) ISLANDS"], 'code' => 'CC', 'status' => 'Active', 'order' => '2'],
            ['id' => '45', 'name' => ["ar" => "كولومبيا", "en" => "COLOMBIA"], 'code' => 'CO', 'status' => 'Active', 'order' => '2'],
            ['id' => '46', 'name' => ["ar" => "جزر القمر", "en" => "COMOROS"], 'code' => 'KM', 'status' => 'Active', 'order' => '2'],
            ['id' => '47', 'name' => ["ar" => "الكونغو - برازافيل", "en" => "CONGO"], 'code' => 'CG', 'status' => 'Active', 'order' => '2'],
            ['id' => '48', 'name' => ["ar" => "جمهورية الكونغو الديمقراطية", "en" => "CONGO, THE DEMOCRATIC REPUBLIC OF THE"], 'code' => 'CD', 'status' => 'Active', 'order' => '2'],
            ['id' => '49', 'name' => ["ar" => "جزر كوك", "en" => "COOK ISLANDS"], 'code' => 'CK', 'status' => 'Active', 'order' => '2'],
            ['id' => '50', 'name' => ["ar" => "كوستاريكا", "en" => "COSTA RICA"], 'code' => 'CR', 'status' => 'Active', 'order' => '2'],
            ['id' => '51', 'name' => ["ar" => "كوبا", "en" => "CUBA"], 'code' => 'CU', 'status' => 'Active', 'order' => '2'],
            ['id' => '53', 'name' => ["ar" => "قبرص", "en" => "CYPRUS"], 'code' => 'CY', 'status' => 'Active', 'order' => '2'],
            ['id' => '54', 'name' => ["ar" => "الدانمرك", "en" => "DENMARK"], 'code' => 'DK', 'status' => 'Active', 'order' => '2'],
            ['id' => '55', 'name' => ["ar" => "جيبوتي", "en" => "DJIBOUTI"], 'code' => 'DJ', 'status' => 'Active', 'order' => '2'],
            ['id' => '56', 'name' => ["ar" => "دومينيكا", "en" => "DOMINICA"], 'code' => 'DM', 'status' => 'Active', 'order' => '2'],
            ['id' => '57', 'name' => ["ar" => "جمهورية الدومينيك", "en" => "DOMINICAN REPUBLIC"], 'code' => 'DO', 'status' => 'Active', 'order' => '2'],
            ['id' => '58', 'name' => ["ar" => "ألمانيا", "en" => "GERMANY"], 'code' => 'DE', 'status' => 'Active', 'order' => '2'],
            ['id' => '59', 'name' => ["ar" => "الاكوادور", "en" => "ECUADOR"], 'code' => 'EC', 'status' => 'Active', 'order' => '2'],
            ['id' => '60', 'name' => ["ar" => "مصر", "en" => "EGYPT"], 'code' => 'EG', 'status' => 'Active', 'order' => '2'],
            ['id' => '61', 'name' => ["ar" => "السلفادور", "en" => "EL SALVADOR"], 'code' => 'SV', 'status' => 'Active', 'order' => '2'],
            ['id' => '62', 'name' => ["ar" => "غينيا الاستوائية", "en" => "EQUATORIAL GUINEA"], 'code' => 'GQ', 'status' => 'Active', 'order' => '2'],
            ['id' => '63', 'name' => ["ar" => "اريتريا", "en" => "ERITREA"], 'code' => 'ER', 'status' => 'Active', 'order' => '2'],
            ['id' => '64', 'name' => ["ar" => "استونيا", "en" => "ESTONIA"], 'code' => 'EE', 'status' => 'Active', 'order' => '2'],
            ['id' => '65', 'name' => ["ar" => "اثيوبيا", "en" => "ETHIOPIA"], 'code' => 'ET', 'status' => 'Active', 'order' => '2'],
            ['id' => '66', 'name' => ["ar" => "جزر فارو", "en" => "FAROE ISLANDS"], 'code' => 'FO', 'status' => 'Active', 'order' => '2'],
            ['id' => '67', 'name' => ["ar" => "جزر فوكلاند", "en" => "FALKLAND ISLANDS (MALVINAS)"], 'code' => 'FK', 'status' => 'Active', 'order' => '2'],
            ['id' => '68', 'name' => ["ar" => "فيجي", "en" => "FIJI"], 'code' => 'FJ', 'status' => 'Active', 'order' => '2'],
            ['id' => '69', 'name' => ["ar" => "الفيلبين", "en" => "PHILIPPINES"], 'code' => 'PH', 'status' => 'Active', 'order' => '2'],
            ['id' => '70', 'name' => ["ar" => "فنلندا", "en" => "FINLAND"], 'code' => 'FI', 'status' => 'Active', 'order' => '2'],
            ['id' => '71', 'name' => ["ar" => "فرنسا", "en" => "FRANCE"], 'code' => 'FR', 'status' => 'Active', 'order' => '2'],
            ['id' => '72', 'name' => ["ar" => "المقاطعات الجنوبية الفرنسية", "en" => "FRENCH SOUTHERN TERRITORIES"], 'code' => 'TF', 'status' => 'Active', 'order' => '2'],
            ['id' => '73', 'name' => ["ar" => "غويانا", "en" => "FRENCH GUIANA"], 'code' => 'GF', 'status' => 'Active', 'order' => '2'],
            ['id' => '74', 'name' => ["ar" => "بولينيزيا الفرنسية", "en" => "FRENCH POLYNESIA"], 'code' => 'PF', 'status' => 'Active', 'order' => '2'],
            ['id' => '75', 'name' => ["ar" => "الجابون", "en" => "GABON"], 'code' => 'GA', 'status' => 'Active', 'order' => '2'],
            ['id' => '76', 'name' => ["ar" => "غامبيا", "en" => "GAMBIA"], 'code' => 'GM', 'status' => 'Active', 'order' => '2'],
            ['id' => '77', 'name' => ["ar" => "جورجيا", "en" => "GEORGIA"], 'code' => 'GE', 'status' => 'Active', 'order' => '2'],
            ['id' => '78', 'name' => ["ar" => "غانا", "en" => "GHANA"], 'code' => 'GH', 'status' => 'Active', 'order' => '2'],
            ['id' => '79', 'name' => ["ar" => "جبل طارق", "en" => "GIBRALTAR"], 'code' => 'GI', 'status' => 'Active', 'order' => '2'],
            ['id' => '80', 'name' => ["ar" => "جرينادا", "en" => "GRENADA"], 'code' => 'GD', 'status' => 'Active', 'order' => '2'],
            ['id' => '81', 'name' => ["ar" => "اليونان", "en" => "GREECE"], 'code' => 'GR', 'status' => 'Active', 'order' => '2'],
            ['id' => '82', 'name' => ["ar" => "جرينلاند", "en" => "GREENLAND"], 'code' => 'GL', 'status' => 'Active', 'order' => '2'],
            ['id' => '83', 'name' => ["ar" => "جوادلوب", "en" => "GUADELOUPE"], 'code' => 'GP', 'status' => 'Active', 'order' => '2'],
            ['id' => '84', 'name' => ["ar" => "جوام", "en" => "GUAM"], 'code' => 'GU', 'status' => 'Active', 'order' => '2'],
            ['id' => '85', 'name' => ["ar" => "جواتيمالا", "en" => "GUATEMALA"], 'code' => 'GT', 'status' => 'Active', 'order' => '2'],
            ['id' => '87', 'name' => ["ar" => "غينيا", "en" => "GUINEA"], 'code' => 'GN', 'status' => 'Active', 'order' => '2'],
            ['id' => '88', 'name' => ["ar" => "غينيا بيساو", "en" => "GUINEA-BISSAU"], 'code' => 'GW', 'status' => 'Active', 'order' => '2'],
            ['id' => '89', 'name' => ["ar" => "غيانا", "en" => "GUYANA"], 'code' => 'GY', 'status' => 'Active', 'order' => '2'],
            ['id' => '90', 'name' => ["ar" => "هايتي", "en" => "HAITI"], 'code' => 'HT', 'status' => 'Active', 'order' => '2'],
            ['id' => '91', 'name' => ["ar" => "جزيرة هيرد وماكدونالد", "en" => "HEARD ISLAND AND MCDONALD ISLANDS"], 'code' => 'HM', 'status' => 'Active', 'order' => '2'],
            ['id' => '92', 'name' => ["ar" => "هندوراس", "en" => "HONDURAS"], 'code' => 'HN', 'status' => 'Active', 'order' => '2'],
            ['id' => '93', 'name' => ["ar" => "المجر", "en" => "HUNGARY"], 'code' => 'HU', 'status' => 'Active', 'order' => '2'],
            ['id' => '94', 'name' => ["ar" => "هونج كونج الصينية", "en" => "HONG KONG"], 'code' => 'HK', 'status' => 'Active', 'order' => '2'],
            ['id' => '95', 'name' => ["ar" => "أيرلندا", "en" => "IRELAND"], 'code' => 'IE', 'status' => 'Active', 'order' => '2'],
            ['id' => '96', 'name' => ["ar" => "أيسلندا", "en" => "ICELAND"], 'code' => 'IS', 'status' => 'Active', 'order' => '2'],
            ['id' => '97', 'name' => ["ar" => "الهند", "en" => "INDIA"], 'code' => 'IN', 'status' => 'Active', 'order' => '2'],
            ['id' => '98', 'name' => ["ar" => "اندونيسيا", "en" => "INDONESIA"], 'code' => 'ID', 'status' => 'Active', 'order' => '2'],
            ['id' => '99', 'name' => ["ar" => "العراق", "en" => "IRAQ"], 'code' => 'IQ', 'status' => 'Active', 'order' => '2'],
            ['id' => '100', 'name' => ["ar" => "ايران", "en" => "IRAN, ISLAMIC REPUBLIC OF"], 'code' => 'IR', 'status' => 'Active', 'order' => '2'],
            ['id' => '102', 'name' => ["ar" => "ايطاليا", "en" => "ITALY"], 'code' => 'IT', 'status' => 'Active', 'order' => '2'],
            ['id' => '103', 'name' => ["ar" => "ساحل العاج", "en" => "COTE D IVOIRE"], 'code' => 'CI', 'status' => 'Active', 'order' => '2'],
            ['id' => '104', 'name' => ["ar" => "جامايكا", "en" => "JAMAICA"], 'code' => 'JM', 'status' => 'Active', 'order' => '2'],
            ['id' => '105', 'name' => ["ar" => "اليابان", "en" => "JAPAN"], 'code' => 'JP', 'status' => 'Active', 'order' => '2'],
            ['id' => '106', 'name' => ["ar" => "اليمن", "en" => "YEMEN"], 'code' => 'YE', 'status' => 'Active', 'order' => '2'],
            ['id' => '108', 'name' => ["ar" => "الأردن", "en" => "JORDAN"], 'code' => 'JO', 'status' => 'Active', 'order' => '2'],
            ['id' => '109', 'name' => ["ar" => "جزر الكايمن", "en" => "CAYMAN ISLANDS"], 'code' => 'KY', 'status' => 'Active', 'order' => '2'],
            ['id' => '110', 'name' => ["ar" => "الرأس الأخضر", "en" => "CAPE VERDE"], 'code' => 'CV', 'status' => 'Active', 'order' => '2'],
            ['id' => '111', 'name' => ["ar" => "الكاميرون", "en" => "CAMEROON"], 'code' => 'CM', 'status' => 'Active', 'order' => '2'],
            ['id' => '112', 'name' => ["ar" => "كازاخستان", "en" => "KAZAKSTAN"], 'code' => 'KZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '113', 'name' => ["ar" => "كينيا", "en" => "KENYA"], 'code' => 'KE', 'status' => 'Active', 'order' => '2'],
            ['id' => '114', 'name' => ["ar" => "قرغيزستان", "en" => "KYRGYZSTAN"], 'code' => 'KG', 'status' => 'Active', 'order' => '2'],
            ['id' => '115', 'name' => ["ar" => "كيريباتي", "en" => "KIRIBATI"], 'code' => 'KI', 'status' => 'Active', 'order' => '2'],
            ['id' => '116', 'name' => ["ar" => "جزر الولايات المتحدة البعيدة الصغيرة", "en" => "UNITED STATES MINOR OUTLYING ISLANDS"], 'code' => 'UM', 'status' => 'Active', 'order' => '2'],
            ['id' => '117', 'name' => ["ar" => "الكويت", "en" => "KUWAIT"], 'code' => 'KW', 'status' => 'Active', 'order' => '2'],
            ['id' => '118', 'name' => ["ar" => "كرواتيا", "en" => "CROATIA"], 'code' => 'HR', 'status' => 'Active', 'order' => '2'],
            ['id' => '119', 'name' => ["ar" => "لاوس", "en" => "LAO PEOPLES DEMOCRATIC REPUBLIC"], 'code' => 'LA', 'status' => 'Active', 'order' => '2'],
            ['id' => '120', 'name' => ["ar" => "ليسوتو", "en" => "LESOTHO"], 'code' => 'LS', 'status' => 'Active', 'order' => '2'],
            ['id' => '121', 'name' => ["ar" => "لاتفيا", "en" => "LATVIA"], 'code' => 'LV', 'status' => 'Active', 'order' => '2'],
            ['id' => '122', 'name' => ["ar" => "لبنان", "en" => "LEBANON"], 'code' => 'LB', 'status' => 'Active', 'order' => '2'],
            ['id' => '123', 'name' => ["ar" => "ليبيريا", "en" => "LIBERIA"], 'code' => 'LR', 'status' => 'Active', 'order' => '2'],
            ['id' => '124', 'name' => ["ar" => "ليبيا", "en" => "LIBYAN ARAB JAMAHIRIYA"], 'code' => 'LY', 'status' => 'Active', 'order' => '2'],
            ['id' => '125', 'name' => ["ar" => "ليختنشتاين", "en" => "LIECHTENSTEIN"], 'code' => 'LI', 'status' => 'Active', 'order' => '2'],
            ['id' => '126', 'name' => ["ar" => "ليتوانيا", "en" => "LITHUANIA"], 'code' => 'LT', 'status' => 'Active', 'order' => '2'],
            ['id' => '127', 'name' => ["ar" => "لوكسمبورج", "en" => "LUXEMBOURG"], 'code' => 'LU', 'status' => 'Active', 'order' => '2'],
            ['id' => '128', 'name' => ["ar" => "ماكاو الصينية", "en" => "MACAU"], 'code' => 'MO', 'status' => 'Active', 'order' => '2'],
            ['id' => '129', 'name' => ["ar" => "مقدونيا", "en" => "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"], 'code' => 'MK', 'status' => 'Active', 'order' => '2'],
            ['id' => '130', 'name' => ["ar" => "مدغشقر", "en" => "MADAGASCAR"], 'code' => 'MG', 'status' => 'Active', 'order' => '2'],
            ['id' => '131', 'name' => ["ar" => "ملاوي", "en" => "MALAWI"], 'code' => 'MW', 'status' => 'Active', 'order' => '2'],
            ['id' => '132', 'name' => ["ar" => "جزر الملديف", "en" => "MALDIVES"], 'code' => 'MV', 'status' => 'Active', 'order' => '2'],
            ['id' => '133', 'name' => ["ar" => "ماليزيا", "en" => "MALAYSIA"], 'code' => 'MY', 'status' => 'Active', 'order' => '2'],
            ['id' => '134', 'name' => ["ar" => "مالي", "en" => "MALI"], 'code' => 'ML', 'status' => 'Active', 'order' => '2'],
            ['id' => '135', 'name' => ["ar" => "مالطا", "en" => "MALTA"], 'code' => 'MT', 'status' => 'Active', 'order' => '2'],
            ['id' => '137', 'name' => ["ar" => "المغرب", "en" => "MOROCCO"], 'code' => 'MA', 'status' => 'Active', 'order' => '2'],
            ['id' => '138', 'name' => ["ar" => "جزر المارشال", "en" => "MARSHALL ISLANDS"], 'code' => 'MH', 'status' => 'Active', 'order' => '2'],
            ['id' => '139', 'name' => ["ar" => "مارتينيك", "en" => "MARTINIQUE"], 'code' => 'MQ', 'status' => 'Active', 'order' => '2'],
            ['id' => '140', 'name' => ["ar" => "موريتانيا", "en" => "MAURITANIA"], 'code' => 'MR', 'status' => 'Active', 'order' => '2'],
            ['id' => '141', 'name' => ["ar" => "موريشيوس", "en" => "MAURITIUS"], 'code' => 'MU', 'status' => 'Active', 'order' => '2'],
            ['id' => '142', 'name' => ["ar" => "مايوت", "en" => "MAYOTTE"], 'code' => 'YT', 'status' => 'Active', 'order' => '2'],
            ['id' => '143', 'name' => ["ar" => "المكسيك", "en" => "MEXICO"], 'code' => 'MX', 'status' => 'Active', 'order' => '2'],
            ['id' => '144', 'name' => ["ar" => "ميكرونيزيا", "en" => "MICRONESIA, FEDERATED STATES OF"], 'code' => 'FM', 'status' => 'Active', 'order' => '2'],
            ['id' => '145', 'name' => ["ar" => "مولدافيا", "en" => "MOLDOVA, REPUBLIC OF"], 'code' => 'MD', 'status' => 'Active', 'order' => '2'],
            ['id' => '146', 'name' => ["ar" => "موناكو", "en" => "MONACO"], 'code' => 'MC', 'status' => 'Active', 'order' => '2'],
            ['id' => '147', 'name' => ["ar" => "منغوليا", "en" => "MONGOLIA"], 'code' => 'MN', 'status' => 'Active', 'order' => '2'],
            ['id' => '149', 'name' => ["ar" => "مونتسرات", "en" => "MONTSERRAT"], 'code' => 'MS', 'status' => 'Active', 'order' => '2'],
            ['id' => '150', 'name' => ["ar" => "موزمبيق", "en" => "MOZAMBIQUE"], 'code' => 'MZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '151', 'name' => ["ar" => "ميانمار", "en" => "MYANMAR"], 'code' => 'MM', 'status' => 'Active', 'order' => '2'],
            ['id' => '152', 'name' => ["ar" => "ناميبيا", "en" => "NAMIBIA"], 'code' => 'NA', 'status' => 'Active', 'order' => '2'],
            ['id' => '153', 'name' => ["ar" => "نورو", "en" => "NAURU"], 'code' => 'NR', 'status' => 'Active', 'order' => '2'],
            ['id' => '154', 'name' => ["ar" => "هولندا", "en" => "NETHERLANDS"], 'code' => 'NL', 'status' => 'Active', 'order' => '2'],
            ['id' => '155', 'name' => ["ar" => "نيبال", "en" => "NEPAL"], 'code' => 'NP', 'status' => 'Active', 'order' => '2'],
            ['id' => '156', 'name' => ["ar" => "نيكاراجوا", "en" => "NICARAGUA"], 'code' => 'NI', 'status' => 'Active', 'order' => '2'],
            ['id' => '157', 'name' => ["ar" => "كاليدونيا الجديدة", "en" => "NEW CALEDONIA"], 'code' => 'NC', 'status' => 'Active', 'order' => '2'],
            ['id' => '158', 'name' => ["ar" => "نيوزيلاندا", "en" => "NEW ZEALAND"], 'code' => 'NZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '159', 'name' => ["ar" => "النيجر", "en" => "NIGER"], 'code' => 'NE', 'status' => 'Active', 'order' => '2'],
            ['id' => '160', 'name' => ["ar" => "نيجيريا", "en" => "NIGERIA"], 'code' => 'NG', 'status' => 'Active', 'order' => '2'],
            ['id' => '161', 'name' => ["ar" => "نيوي", "en" => "NIUE"], 'code' => 'NU', 'status' => 'Active', 'order' => '2'],
            ['id' => '162', 'name' => ["ar" => "جزر ماريانا الشمالية", "en" => "NORTHERN MARIANA ISLANDS"], 'code' => 'MP', 'status' => 'Active', 'order' => '2'],
            ['id' => '163', 'name' => ["ar" => "كوريا الشمالية", "en" => "KOREA DEMOCRATIC PEOPLES REPUBLIC OF"], 'code' => 'KP', 'status' => 'Active', 'order' => '2'],
            ['id' => '164', 'name' => ["ar" => "النرويج", "en" => "NORWAY"], 'code' => 'NO', 'status' => 'Active', 'order' => '2'],
            ['id' => '165', 'name' => ["ar" => "جزيرة نورفوك", "en" => "NORFOLK ISLAND"], 'code' => 'NF', 'status' => 'Active', 'order' => '2'],
            ['id' => '166', 'name' => ["ar" => "أوغندا", "en" => "UGANDA"], 'code' => 'UG', 'status' => 'Active', 'order' => '2'],
            ['id' => '167', 'name' => ["ar" => "أوكرانيا", "en" => "UKRAINE"], 'code' => 'UA', 'status' => 'Active', 'order' => '2'],
            ['id' => '168', 'name' => ["ar" => "أوزبكستان", "en" => "UZBEKISTAN"], 'code' => 'UZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '169', 'name' => ["ar" => "عمان", "en" => "OMAN"], 'code' => 'OM', 'status' => 'Active', 'order' => '2'],
            ['id' => '170', 'name' => ["ar" => "النمسا", "en" => "AUSTRIA"], 'code' => 'AT', 'status' => 'Active', 'order' => '2'],
            ['id' => '172', 'name' => ["ar" => "باكستان", "en" => "PAKISTAN"], 'code' => 'PK', 'status' => 'Active', 'order' => '2'],
            ['id' => '173', 'name' => ["ar" => "بالاو", "en" => "PALAU"], 'code' => 'PW', 'status' => 'Active', 'order' => '2'],
            ['id' => '174', 'name' => ["ar" => "فلسطين", "en" => "PALESTINE"], 'code' => 'PS', 'status' => 'Active', 'order' => '2'],
            ['id' => '175', 'name' => ["ar" => "بنما", "en" => "PANAMA"], 'code' => 'PA', 'status' => 'Active', 'order' => '2'],
            ['id' => '176', 'name' => ["ar" => "بابوا غينيا الجديدة", "en" => "PAPUA NEW GUINEA"], 'code' => 'PG', 'status' => 'Active', 'order' => '2'],
            ['id' => '177', 'name' => ["ar" => "باراجواي", "en" => "PARAGUAY"], 'code' => 'PY', 'status' => 'Active', 'order' => '2'],
            ['id' => '178', 'name' => ["ar" => "بيرو", "en" => "PERU"], 'code' => 'PE', 'status' => 'Active', 'order' => '2'],
            ['id' => '179', 'name' => ["ar" => "بتكايرن", "en" => "PITCAIRN"], 'code' => 'PN', 'status' => 'Active', 'order' => '2'],
            ['id' => '180', 'name' => ["ar" => "بولندا", "en" => "POLAND"], 'code' => 'PL', 'status' => 'Active', 'order' => '2'],
            ['id' => '181', 'name' => ["ar" => "البرتغال", "en" => "PORTUGAL"], 'code' => 'PT', 'status' => 'Active', 'order' => '2'],
            ['id' => '182', 'name' => ["ar" => "بورتوريكو", "en" => "PUERTO RICO"], 'code' => 'PR', 'status' => 'Active', 'order' => '2'],
            ['id' => '183', 'name' => ["ar" => "قطر", "en" => "QATAR"], 'code' => 'QA', 'status' => 'Active', 'order' => '2'],
            ['id' => '184', 'name' => ["ar" => "روينيون", "en" => "REUNION"], 'code' => 'RE', 'status' => 'Active', 'order' => '2'],
            ['id' => '185', 'name' => ["ar" => "رومانيا", "en" => "ROMANIA"], 'code' => 'RO', 'status' => 'Active', 'order' => '2'],
            ['id' => '186', 'name' => ["ar" => "روسيا", "en" => "RUSSIAN FEDERATION"], 'code' => 'RU', 'status' => 'Active', 'order' => '2'],
            ['id' => '187', 'name' => ["ar" => "رواندا", "en" => "RWANDA"], 'code' => 'RW', 'status' => 'Active', 'order' => '2'],
            ['id' => '189', 'name' => ["ar" => "سانت كيتس ونيفيس", "en" => "SAINT KITTS AND NEVIS"], 'code' => 'KN', 'status' => 'Active', 'order' => '2'],
            ['id' => '190', 'name' => ["ar" => "سانت لوسيا", "en" => "SAINT LUCIA"], 'code' => 'LC', 'status' => 'Active', 'order' => '2'],
            ['id' => '191', 'name' => ["ar" => "سانت بيير وميكولون", "en" => "SAINT PIERRE AND MIQUELON"], 'code' => 'PM', 'status' => 'Active', 'order' => '2'],
            ['id' => '192', 'name' => ["ar" => "سانت فنسنت وغرنادين", "en" => "SAINT VINCENT AND THE GRENADINES"], 'code' => 'VC', 'status' => 'Active', 'order' => '2'],
            ['id' => '193', 'name' => ["ar" => "جزر سليمان", "en" => "SOLOMON ISLANDS"], 'code' => 'SB', 'status' => 'Active', 'order' => '2'],
            ['id' => '194', 'name' => ["ar" => "ساموا", "en" => "SAMOA"], 'code' => 'WS', 'status' => 'Active', 'order' => '2'],
            ['id' => '195', 'name' => ["ar" => "سان مارينو", "en" => "SAN MARINO"], 'code' => 'SM', 'status' => 'Active', 'order' => '2'],
            ['id' => '196', 'name' => ["ar" => "المملكة العربية السعودية", "en" => "SAUDI ARABIA"], 'code' => 'SA', 'status' => 'Active', 'order' => '2'],
            ['id' => '197', 'name' => ["ar" => "ساو تومي وبرينسيبي", "en" => "SAO TOME AND PRINCIPE"], 'code' => 'ST', 'status' => 'Active', 'order' => '2'],
            ['id' => '198', 'name' => ["ar" => "السنغال", "en" => "SENEGAL"], 'code' => 'SN', 'status' => 'Active', 'order' => '2'],
            ['id' => '200', 'name' => ["ar" => "سيشل", "en" => "SEYCHELLES"], 'code' => 'SC', 'status' => 'Active', 'order' => '2'],
            ['id' => '201', 'name' => ["ar" => "سيراليون", "en" => "SIERRA LEONE"], 'code' => 'SL', 'status' => 'Active', 'order' => '2'],
            ['id' => '202', 'name' => ["ar" => "سنغافورة", "en" => "SINGAPORE"], 'code' => 'SG', 'status' => 'Active', 'order' => '2'],
            ['id' => '203', 'name' => ["ar" => "سانت هيلنا", "en" => "SAINT HELENA"], 'code' => 'SH', 'status' => 'Active', 'order' => '2'],
            ['id' => '205', 'name' => ["ar" => "سلوفينيا", "en" => "SLOVENIA"], 'code' => 'SI', 'status' => 'Active', 'order' => '2'],
            ['id' => '206', 'name' => ["ar" => "سلوفاكيا", "en" => "SLOVAKIA"], 'code' => 'SK', 'status' => 'Active', 'order' => '2'],
            ['id' => '207', 'name' => ["ar" => "السودان", "en" => "SUDAN"], 'code' => 'SD', 'status' => 'Active', 'order' => '2'],
            ['id' => '208', 'name' => ["ar" => "الصومال", "en" => "SOMALIA"], 'code' => 'SO', 'status' => 'Active', 'order' => '2'],
            ['id' => '209', 'name' => ["ar" => "أسبانيا", "en" => "SPAIN"], 'code' => 'ES', 'status' => 'Active', 'order' => '2'],
            ['id' => '210', 'name' => ["ar" => "سفالبارد وجان مايان", "en" => "SVALBARD AND JAN MAYEN"], 'code' => 'SJ', 'status' => 'Active', 'order' => '2'],
            ['id' => '211', 'name' => ["ar" => "سريلانكا", "en" => "SRI LANKA"], 'code' => 'LK', 'status' => 'Active', 'order' => '2'],
            ['id' => '212', 'name' => ["ar" => "سورينام", "en" => "SURINAME"], 'code' => 'SR', 'status' => 'Active', 'order' => '2'],
            ['id' => '213', 'name' => ["ar" => "سوازيلاند", "en" => "SWAZILAND"], 'code' => 'SZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '214', 'name' => ["ar" => "سوريا", "en" => "SYRIAN ARAB REPUBLIC"], 'code' => 'SY', 'status' => 'Active', 'order' => '2'],
            ['id' => '215', 'name' => ["ar" => "طاجكستان", "en" => "TAJIKISTAN"], 'code' => 'TJ', 'status' => 'Active', 'order' => '2'],
            ['id' => '216', 'name' => ["ar" => "تايوان", "en" => "TAIWAN, PROVINCE OF CHINA"], 'code' => 'TW', 'status' => 'Active', 'order' => '2'],
            ['id' => '217', 'name' => ["ar" => "تانزانيا", "en" => "TANZANIA, UNITED REPUBLIC OF"], 'code' => 'TZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '218', 'name' => ["ar" => "تايلند", "en" => "THAILAND"], 'code' => 'TH', 'status' => 'Active', 'order' => '2'],
            ['id' => '219', 'name' => ["ar" => "توجو", "en" => "TOGO"], 'code' => 'TG', 'status' => 'Active', 'order' => '2'],
            ['id' => '220', 'name' => ["ar" => "توكيلو", "en" => "TOKELAU"], 'code' => 'TK', 'status' => 'Active', 'order' => '2'],
            ['id' => '221', 'name' => ["ar" => "تونجا", "en" => "TONGA"], 'code' => 'TO', 'status' => 'Active', 'order' => '2'],
            ['id' => '222', 'name' => ["ar" => "ترينيداد وتوباغو", "en" => "TRINIDAD AND TOBAGO"], 'code' => 'TT', 'status' => 'Active', 'order' => '2'],
            ['id' => '223', 'name' => ["ar" => "تشاد", "en" => "CHAD"], 'code' => 'TD', 'status' => 'Active', 'order' => '2'],
            ['id' => '224', 'name' => ["ar" => "جمهورية التشيك", "en" => "CZECH REPUBLIC"], 'code' => 'CZ', 'status' => 'Active', 'order' => '2'],
            ['id' => '225', 'name' => ["ar" => "تونس", "en" => "TUNISIA"], 'code' => 'TN', 'status' => 'Active', 'order' => '2'],
            ['id' => '226', 'name' => ["ar" => "تركيا", "en" => "TURKEY"], 'code' => 'TR', 'status' => 'Active', 'order' => '2'],
            ['id' => '227', 'name' => ["ar" => "تركمانستان", "en" => "TURKMENISTAN"], 'code' => 'TM', 'status' => 'Active', 'order' => '2'],
            ['id' => '228', 'name' => ["ar" => "جزر الترك وجايكوس", "en" => "TURKS AND CAICOS ISLANDS"], 'code' => 'TC', 'status' => 'Active', 'order' => '2'],
            ['id' => '229', 'name' => ["ar" => "توفالو", "en" => "TUVALU"], 'code' => 'TV', 'status' => 'Active', 'order' => '2'],
            ['id' => '230', 'name' => ["ar" => "أورجواي", "en" => "URUGUAY"], 'code' => 'UY', 'status' => 'Active', 'order' => '2'],
            ['id' => '231', 'name' => ["ar" => "فانواتو", "en" => "VANUATU"], 'code' => 'VU', 'status' => 'Active', 'order' => '2'],
            ['id' => '232', 'name' => ["ar" => "الفاتيكان", "en" => "HOLY SEE (VATICAN CITY STATE)"], 'code' => 'VA', 'status' => 'Active', 'order' => '2'],
            ['id' => '233', 'name' => ["ar" => "فنزويلا", "en" => "VENEZUELA"], 'code' => 'VE', 'status' => 'Active', 'order' => '2'],
            ['id' => '234', 'name' => ["ar" => "الامارات العربية المتحدة", "en" => "UNITED ARAB EMIRATES"], 'code' => 'AE', 'status' => 'Active', 'order' => '2'],
            ['id' => '235', 'name' => ["ar" => "الولايات المتحدة الأمريكية", "en" => "UNITED STATES"], 'code' => 'US', 'status' => 'Active', 'order' => '2'],
            ['id' => '236', 'name' => ["ar" => "المملكة المتحدة", "en" => "UNITED KINGDOM"], 'code' => 'GB', 'status' => 'Active', 'order' => '2'],
            ['id' => '237', 'name' => ["ar" => "فيتنام", "en" => "VIET NAM"], 'code' => 'VN', 'status' => 'Active', 'order' => '2'],
            ['id' => '238', 'name' => ["ar" => "جزر والس وفوتونا", "en" => "WALLIS AND FUTUNA"], 'code' => 'WF', 'status' => 'Active', 'order' => '2'],
            ['id' => '239', 'name' => ["ar" => "الصحراء الغربية", "en" => "WESTERN SAHARA"], 'code' => 'EH', 'status' => 'Active', 'order' => '2'],
            ['id' => '240', 'name' => ["ar" => "روسيا البيضاء", "en" => "BELARUS"], 'code' => 'BY', 'status' => 'Active', 'order' => '2'],
            ['id' => '241', 'name' => ["ar" => "زامبيا", "en" => "ZAMBIA"], 'code' => 'ZM', 'status' => 'Active', 'order' => '2'],
            ['id' => '242', 'name' => ["ar" => "زيمبابوي", "en" => "ZIMBABWE"], 'code' => 'ZW', 'status' => 'Active', 'order' => '2'],
            ['id' => '243', 'name' => ["ar" => "جمهورية جنوب افريقيا", "en" => "SOUTH AFRICA"], 'code' => 'ZA', 'status' => 'Active', 'order' => '2'],
            ['id' => '244', 'name' => ["ar" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية", "en" => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"], 'code' => 'GS', 'status' => 'Active', 'order' => '2'],
            ['id' => '245', 'name' => ["ar" => "كوريا الجنوبية", "en" => "KOREA REPUBLIC OF"], 'code' => 'KR', 'status' => 'Active', 'order' => '2'],
            ['id' => '247', 'name' => ["ar" => "السويد", "en" => "SWEDEN"], 'code' => 'SE', 'status' => 'Active', 'order' => '2'],
            ['id' => '248', 'name' => ["ar" => "سويسرا", "en" => "SWITZERLAND"], 'code' => 'CH', 'status' => 'Active', 'order' => '2']
        ];

        Nationality::truncate();

        foreach ($nationalities as $nationality) {
            $nationality_model = new Nationality();
            $nationality_model->id = $nationality['id'];
            $nationality_model->code = $nationality['code'];
            $nationality_model->currency = $nationality['code'];
            $nationality_model->status = $nationality['status'];
            $nationality_model->name = ['ar' => $nationality['name']['ar'], 'en' => $nationality['name']['en']];
            $nationality_model->order = $nationality['order'];
            $nationality_model->save();
        }
    }
}
